from django.contrib import admin
from django.urls import path,include

from api.views import CompanyViewSet
from rest_framework import routers

router=routers.DefaultRouter()
# Routers are used to automatically generate URL patterns for viewsets.
router.register(r'companies',CompanyViewSet)
# routers module from Django REST Framework, which provides utilities for automatically generating URL patterns for API endpoints.
# This registers the CompanyViewSet viewset with the router.
#It associates the viewset with the URL pattern /companies/, meaning that accessing this URL will invoke the views defined in CompanyViewSet.
urlpatterns = [
    path('',include(router.urls))
    # includes the url generated by the router
    # The router.urls attribute automatically generates URL patterns for the registered viewsets, including patterns for listing, creating, retrieving, updating, 
    # and deleting objects based on the viewset's actions (such as those provided by a ModelViewSet).
]

# When the Django application runs, it will include these URL patterns, allowing clients to interact with the Company model(database) through the specified API endpoints, such as /companies/ for listing companies or creating new ones.
# API endpoints typically have a structured URL format 
#  API endpoints serve as the entry points for clients to interact with a web API, allowing them to access resources